### ISSUE TITLE
Using without collection view

### ISSUE THREAD

**Issue by Xpressive** [bakkenbaeck/Viewer#125]
Hi! That's really a great library, i think the only one, which gave ability to customize header/footer view. The only thing that it missed - ability to show photos without collection view. What do you think about adding that functionality?

**Comment by 3lvis** [comment]
Hi @Xpressive,

Sounds like a great idea, sadly I don't think we have plans to add that feature at the moment. If it's something you would like to work on I'm happy to assist you in what's required in order to add that functionality. 

 :)

**Comment by Binlogo** [comment]
@Xpressive  This feature proposal is really great 👍

**Comment by dfmarulanda** [comment]
This idea wasn't implemented?

**Comment by fukemy** [comment]
i think it's would be better if implement datas contain list of (photos, videos) and pass to gallery to present like lightbox.

**Comment by fukemy** [comment]
but lightbox can play video inside gallery show

**Comment by 3lvis** [comment]
Are you talking about https://github.com/hyperoslo/Lightbox?

**Comment by fukemy** [comment]
yeah, sorry for my bad request, i know your library is using for gallery view, lightbox is difference - using for photo view

**Comment by 3lvis** [comment]
I'm trying to fix Lightbox without luck, if you can give it a look it would be great to get your feedback https://github.com/hyperoslo/Lightbox

**Comment by 3lvis** [comment]
It's updated to Swift 5 and Xcode 11 now.

**Comment by fukemy** [comment]
hi, i just run pod install then got this error, can you help? 
```
pod install
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.9.3) is higher than the version of the current executable (1.8.4). Incompatibility issues may arise.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ cea96b43ae868a3303425da4af0f1610eae3b14f
               njhu - git - https://github.com/NJHu/NJSpecs.git @ 535ae44ae577e7c332e3daef6a73ab9df52dc55e
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'DemoLightbox' do
  use_frameworks!
	pod 'Lightbox', path: '../../'
end
```

### Error

```
Errno::EPERM - Operation not permitted @ rb_sysopen - /Users/thehe/Desktop/LightboxViewExample/Lightbox.podspec
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:683:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:683:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:683:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/abstract_external_source.rb:164:in `store_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Operation+not+permitted+%40+rb_sysopen+-+%2FUsers%2Fthehe%2FDesktop%2FLightboxViewExample%2FLightbox.podspec&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
```

**Comment by 3lvis** [comment]
Update your CocoaPods

sudo gem install cocoapods
